ccflags-y += -Idrivers/media/platform/msm/camera_find7
ccflags-y += -Idrivers/media/platform/msm/camera_find7/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_find7/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
