ccflags-y += -Idrivers/media/platform/msm/camera_find7
ccflags-y += -Idrivers/media/platform/msm/camera_find7/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_find7/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
