ccflags-y += -Idrivers/media/platform/msm/camera_find7
ccflags-y += -Idrivers/media/platform/msm/camera_find7/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_find7/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
